create table users (
                          id bigint generated by default as identity,
                          create_time timestamp(6),
                          creator bigint,
                          is_deleted boolean,
                          update_time timestamp(6),
                          updater bigint,
                          activated boolean not null,
                          password varchar(100) not null,
                          username varchar(100) not null,
                          primary key (id)
);
create table authority (
                           name varchar(50) not null,
                           primary key (name)
);
create table user_authority (
                                user_id bigint not null,
                                authority_name varchar(50) not null,
                                primary key (user_id, authority_name)
);