-- ----------------------------------------------------------------
--  MySQL 兼容版本 (已修正 BUSINESS 表的列名为大写)
-- ----------------------------------------------------------------

-- 禁用外键检查，以便顺利创建和插入数据
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
--  Table structure for `USERS`
-- ----------------------------
DROP TABLE IF EXISTS `USERS`;
CREATE TABLE `USERS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATE_TIME` TIMESTAMP(6) NULL,
    `CREATOR` BIGINT NULL,
    `IS_DELETED` TINYINT(1) NULL,
    `UPDATE_TIME` TIMESTAMP(6) NULL,
    `UPDATER` BIGINT NULL,
    `ACTIVATED` TINYINT(1) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    `USERNAME` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`ID`)
);

-- ----------------------------
--  Records of `USERS`
-- ----------------------------
INSERT INTO `USERS` VALUES
(1, NULL, NULL, NULL, NULL, NULL, 1, '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin'),
(2, NULL, NULL, NULL, NULL, NULL, 1, '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user');

-- H2 DDL中指定了从3开始，所以在这里设置
ALTER TABLE `USERS` AUTO_INCREMENT = 3;


-- ----------------------------
--  Table structure for `AUTHORITY`
-- ----------------------------
DROP TABLE IF EXISTS `AUTHORITY`;
CREATE TABLE `AUTHORITY` (
    `NAME` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`NAME`)
);

-- ----------------------------
--  Records of `AUTHORITY`
-- ----------------------------
INSERT INTO `AUTHORITY` VALUES
('ADMIN'),
('USER'),
('BUSINESS');


-- ----------------------------
--  Table structure for `USER_AUTHORITY`
-- ----------------------------
DROP TABLE IF EXISTS `USER_AUTHORITY`;
CREATE TABLE `USER_AUTHORITY` (
    `USER_ID` BIGINT NOT NULL,
    `AUTHORITY_NAME` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`USER_ID`, `AUTHORITY_NAME`)
);

-- ----------------------------
--  Records of `USER_AUTHORITY`
-- ----------------------------
INSERT INTO `USER_AUTHORITY` VALUES
(1, 'ADMIN'),
(1, 'USER'),
(1, 'BUSINESS'),
(2, 'USER');


-- ----------------------------
--  H2的全局临时表被转换为标准表
-- ----------------------------
DROP TABLE IF EXISTS `HT_USERS`;
CREATE TABLE `HT_USERS` (
    `ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `HTE_USERS`;
CREATE TABLE `HTE_USERS` (
    `HTE_IDENTITY` BIGINT NOT NULL AUTO_INCREMENT,
    `ACTIVATED` TINYINT(1) NULL,
    `IS_DELETED` TINYINT(1) NULL,
    `CREATE_TIME` TIMESTAMP(6) NULL,
    `CREATOR` BIGINT NULL,
    `ID` BIGINT NULL,
    `UPDATE_TIME` TIMESTAMP(6) NULL,
    `UPDATER` BIGINT NULL,
    `PASSWORD` VARCHAR(100) NULL,
    `USERNAME` VARCHAR(100) NULL,
    `EMAIL` VARCHAR(255) NULL,
    `FIRST_NAME` VARCHAR(255) NULL,
    `GENDER` VARCHAR(255) NULL,
    `LAST_NAME` VARCHAR(255) NULL,
    `PHONE` VARCHAR(255) NULL,
    `PHOTO` TEXT NULL,
    PRIMARY KEY (`HTE_IDENTITY`)
);

DROP TABLE IF EXISTS `HTE_PERSON`;
CREATE TABLE `HTE_PERSON` (
    `HTE_IDENTITY` BIGINT NOT NULL AUTO_INCREMENT,
    `ACTIVATED` TINYINT(1) NULL,
    `IS_DELETED` TINYINT(1) NULL,
    `CREATE_TIME` TIMESTAMP(6) NULL,
    `CREATOR` BIGINT NULL,
    `ID` BIGINT NULL,
    `UPDATE_TIME` TIMESTAMP(6) NULL,
    `UPDATER` BIGINT NULL,
    `PASSWORD` VARCHAR(100) NULL,
    `USERNAME` VARCHAR(100) NULL,
    `EMAIL` VARCHAR(255) NULL,
    `FIRST_NAME` VARCHAR(255) NULL,
    `GENDER` VARCHAR(255) NULL,
    `LAST_NAME` VARCHAR(255) NULL,
    `PHONE` VARCHAR(255) NULL,
    `PHOTO` TEXT NULL,
    PRIMARY KEY (`HTE_IDENTITY`)
);


-- ----------------------------
--  Table structure for `BUSINESS`
-- ----------------------------
DROP TABLE IF EXISTS `BUSINESS`;
CREATE TABLE `BUSINESS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATE_TIME` TIMESTAMP(6) NULL,
    `CREATOR` BIGINT NULL,
    `IS_DELETED` TINYINT(1) NULL,
    `UPDATE_TIME` TIMESTAMP(6) NULL,
    `UPDATER` BIGINT NULL,
    `BUSINESS_ADDRESS` VARCHAR(255) NULL,
    `BUSINESS_EXPLAIN` VARCHAR(255) NULL,
    `BUSINESS_IMG` TEXT NULL,
    `BUSINESS_NAME` VARCHAR(255) NOT NULL,
    `DELIVERY_PRICE` DECIMAL(10, 2) NULL,
    `ORDER_TYPE_ID` INTEGER NULL,
    `REMARKS` VARCHAR(255) NULL,
    `START_PRICE` DECIMAL(10, 2) NULL,
    `BUSINESS_OWNER_ID` BIGINT NOT NULL,
    `LONGITUDE` DECIMAL(18, 15),
    `LATITUDE` DECIMAL(18, 15),
    PRIMARY KEY (`ID`)
);


-- ----------------------------
--  Table structure for `CART`
-- ----------------------------
DROP TABLE IF EXISTS `CART`;
CREATE TABLE `CART` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATE_TIME` TIMESTAMP(6) NULL,
    `CREATOR` BIGINT NULL,
    `IS_DELETED` TINYINT(1) NULL,
    `UPDATE_TIME` TIMESTAMP(6) NULL,
    `UPDATER` BIGINT NULL,
    `QUANTITY` INTEGER NULL,
    `BUSINESS_ID` BIGINT NOT NULL,
    `CUSTOMER_ID` BIGINT NOT NULL,
    `FOOD_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);


-- ----------------------------
--  Table structure for `DELIVERY_ADDRESS`
-- ----------------------------
DROP TABLE IF EXISTS `DELIVERY_ADDRESS`;
CREATE TABLE `DELIVERY_ADDRESS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATE_TIME` TIMESTAMP(6) NULL,
    `CREATOR` BIGINT NULL,
    `IS_DELETED` TINYINT(1) NULL,
    `UPDATE_TIME` TIMESTAMP(6) NULL,
    `UPDATER` BIGINT NULL,
    `ADDRESS` VARCHAR(255) NULL,
    `CONTACT_NAME` VARCHAR(255) NULL,
    `CONTACT_SEX` INTEGER NULL,
    `CONTACT_TEL` VARCHAR(255) NULL,
    `USER_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);


-- ----------------------------
--  Table structure for `FOOD`
-- ----------------------------
DROP TABLE IF EXISTS `FOOD`;
CREATE TABLE `FOOD` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATE_TIME` TIMESTAMP(6) NULL,
    `CREATOR` BIGINT NULL,
    `IS_DELETED` TINYINT(1) NULL,
    `UPDATE_TIME` TIMESTAMP(6) NULL,
    `UPDATER` BIGINT NULL,
    `FOOD_EXPLAIN` VARCHAR(255) NULL,
    `FOOD_IMG` TEXT NULL,
    `FOOD_NAME` VARCHAR(255) NOT NULL,
    `FOOD_PRICE` DECIMAL(10, 2) NOT NULL,
    `REMARKS` VARCHAR(255) NULL,
    `BUSINESS_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);


-- ----------------------------
--  Table structure for `ORDERDETAILET`
-- ----------------------------
DROP TABLE IF EXISTS `ORDERDETAILET`;
CREATE TABLE `ORDERDETAILET` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATE_TIME` TIMESTAMP(6) NULL,
    `CREATOR` BIGINT NULL,
    `IS_DELETED` TINYINT(1) NULL,
    `UPDATE_TIME` TIMESTAMP(6) NULL,
    `UPDATER` BIGINT NULL,
    `QUANTITY` INTEGER NULL,
    `FOOD_ID` BIGINT NOT NULL,
    `ORDER_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);


-- ----------------------------
--  Table structure for `ORDERS`
-- ----------------------------
DROP TABLE IF EXISTS `ORDERS`;
CREATE TABLE `ORDERS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CREATE_TIME` TIMESTAMP(6) NULL,
    `CREATOR` BIGINT NULL,
    `IS_DELETED` TINYINT(1) NULL,
    `UPDATE_TIME` TIMESTAMP(6) NULL,
    `UPDATER` BIGINT NULL,
    `ORDER_DATE` DATE NULL,
    `ORDER_STATE` INTEGER NULL,
    `ORDER_TOTAL` DECIMAL(10, 2) NULL,
    `BUSINESS_ID` BIGINT NOT NULL,
    `CUSTOMER_ID` BIGINT NOT NULL,
    `ADDRESS_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`)
);


-- ----------------------------
--  Table structure for `PERSON`
-- ----------------------------
DROP TABLE IF EXISTS `PERSON`;
CREATE TABLE `PERSON` (
    `ID` BIGINT NOT NULL,
    `EMAIL` VARCHAR(255) NULL,
    `FIRST_NAME` VARCHAR(255) NULL,
    `GENDER` VARCHAR(255) NULL,
    `LAST_NAME` VARCHAR(255) NULL,
    `PHONE` VARCHAR(255) NULL,
    `PHOTO` TEXT NULL,
    PRIMARY KEY (`ID`)
);


-- ----------------------------
--  Adding Foreign Key Constraints
-- ----------------------------
ALTER TABLE `PERSON` ADD CONSTRAINT `FKT9EIFWFATY2DATNX2RA7LL9DC` FOREIGN KEY (`ID`) REFERENCES `USERS`(`ID`);
ALTER TABLE `CART` ADD CONSTRAINT `FKRYNRWUQBPDHEOCIVCMP9ITSXI` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `USERS`(`ID`);
ALTER TABLE `ORDERS` ADD CONSTRAINT `FKNXIUCB4707442SVU8PPYNG5MD` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `DELIVERY_ADDRESS`(`ID`);
ALTER TABLE `ORDERS` ADD CONSTRAINT `FK6YV9SBEYXJKHKRDB2OPEE19TG` FOREIGN KEY (`BUSINESS_ID`) REFERENCES `BUSINESS`(`ID`);
ALTER TABLE `CART` ADD CONSTRAINT `FK9IDRO6C1M306J5GLP69U15O9J` FOREIGN KEY (`FOOD_ID`) REFERENCES `FOOD`(`ID`);
ALTER TABLE `BUSINESS` ADD CONSTRAINT `FKTM7F6X8BO3O8PK2KRAAWYQ18U` FOREIGN KEY (`BUSINESS_OWNER_ID`) REFERENCES `USERS`(`ID`); -- <-- 已修改为大写
ALTER TABLE `USER_AUTHORITY` ADD CONSTRAINT `FK6KTGLPL5MJOSA283RVKEN2PY5` FOREIGN KEY (`AUTHORITY_NAME`) REFERENCES `AUTHORITY`(`NAME`);
ALTER TABLE `ORDERS` ADD CONSTRAINT `FKSJFS85QF6VMCURLX43CNC16GY` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `USERS`(`ID`);
ALTER TABLE `DELIVERY_ADDRESS` ADD CONSTRAINT `FKLUNOAQ6LSL5D75TKBG3ALRN6U` FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`ID`);
ALTER TABLE `ORDERDETAILET` ADD CONSTRAINT `FKAFCBYJTSRERL3NB0MAFB089YS` FOREIGN KEY (`FOOD_ID`) REFERENCES `FOOD`(`ID`);
ALTER TABLE `CART` ADD CONSTRAINT `FKGVN8S674RPIFKSI4A6UAQ9YMH` FOREIGN KEY (`BUSINESS_ID`) REFERENCES `BUSINESS`(`ID`);
ALTER TABLE `ORDERDETAILET` ADD CONSTRAINT `FKJ78B4W018TI2FM1TH2Y7RIP7P` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS`(`ID`);
ALTER TABLE `FOOD` ADD CONSTRAINT `FK7AACVFJDYBTGIW2TB7VM7NU72` FOREIGN KEY (`BUSINESS_ID`) REFERENCES `BUSINESS`(`ID`);
ALTER TABLE `USER_AUTHORITY` ADD CONSTRAINT `FKHI46VU7680Y1HWVMNNUH4CYBX` FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`ID`);


-- 重新启用外键检查
SET FOREIGN_KEY_CHECKS=1;